### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by harisaurus** [harisaurus/llc-jobs#2]
- [ ] 1. Change the Logo in the header to be the `CLC-Logo-Job-Board-Header.svg` file in the folder. 

- [ ] 2. Make the header background white instead of black and the nav links red with underlines on hover like the staging site. `http://canadalearningcode.ca/staging-rebrand`

- [ ] 3. Add an H1 to the page that says "Jobs" to replace the little jobs in a circle in the current logo. The H1 should be as per the brand guidelines, Maax Bold font, font-size, 85px. You can see for reference headings in the staging site http://canadalearningcode.ca/staging-rebrand

- [ ] 4. Replace the LLC Pink `#b1009a` colour on the app with the new CLC Red `#ef0919`
(See CLC-Identity-StandardsGuide-v1_170709. pdf for more info)

- [ ] 5. Replace the lighter pink colour used to highlight a job with the light cyan colour option in guidelines `#d2fbf9` 

- [ ] 6. Replace the default dark grey/black with our own brand guidelines black: `#2c2c2c`

- [ ] 7. Replace the green of the Permanent/Contract labels in the jobs list with one of the guide's accent colours. Secondary red for example, or grey. Whatever looks better. 

- [ ] 8. Replace the grey of the "Post a Job' box with brand grey: `#efefed`

- [ ] 9. Change Ladies Learning Code in the footer to Canada Learning Code, linked to http://canadalearningcode.ca 

- [ ] 10. Change all fonts according to the guidelines: Maax regular for text and Maax Bold for headings. I have included a folder with the Maax font.
